graylog_server_version: "0.20.2"
graylog_server_prefix: "/usr/local"
graylog_server_dir: "#{graylog_server_prefix}/graylog2-server-#{graylog_server_version}"
graylog_server_pid_file: "/var/run/graylog-server.pid"
graylog_server_port: 12201
graylog_server_syslog_port: 12514

graylog_web_version: "0.20.2"
graylog_web_prefix: "/usr/local"
graylog_web_dir: "#{graylog_web_prefix}/graylog2-web-interface-#{graylog_web_version}"
graylog_web_pid_file: "/var/run/graylog-web.pid"
graylog_web_port: 9000

graylog_web_username: admin
graylog_web_password: admin1

graylog_mongo_database: graylog2
graylog_elasticsearch_index: "graylog2_#{Rubber.env}"

web_tools_proxies:
  graylog:
    role: graylog_web
    port: "#{graylog_web_port}"
    path: /
  graylog_server_api_browser:
    role: graylog_server
    port: 12900
    path: /api-browser/

role_dependencies:
  graylog_server: [graylog_mongodb, graylog_elasticsearch]
  graylog_mongodb: [mongodb]
  graylog_elasticsearch: [elasticsearch]

roles:
  graylog_server:
    packages: [openjdk-7-jdk, mongodb-10gen]
  graylog_web:
    packages: [openjdk-7-jdk]

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_server_secret: 58aaa92b5317e010e9144e92667fed3e6981e5a72685cf6d1d9c4ba9ef3d1090c9813146d48f1ea25b815caf59b524bb8b0174406def16efa3070efd794f887599a43ac067038260eb41300d2acecef6752dde0542568b7cbcfd4f5c770c9e2f

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_web_secret: 34ca3e6edecc9e0487020761d02bef433fecf296bd61eea09f580b647c294a5a55b3dbd27b8995a721b4e5e3991271d201b6178a398bc7d12758580f80108356f00b0c86be41cb532a0e77b9b6074871198e06355fa9074477da411f16b66c18
